"""
========================================================
AnomaliNet Detection Service
========================================================
Runs the AI detection engine and receives the
authoritative result generated by that exact run.
========================================================
"""

import os
import subprocess
import sys
import json
import traceback


# =====================================================
# PROJECT ROOT
# =====================================================

PROJECT_ROOT = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        ".."
    )
)


# =====================================================
# FOLDERS
# =====================================================

OUTPUT_FOLDER = os.path.join(
    PROJECT_ROOT,
    "frontend",
    "static",
    "processed_videos"
)

SNAPSHOT_FOLDER = os.path.join(
    PROJECT_ROOT,
    "frontend",
    "static",
    "saved_incidents"
)

SUMMARY_FOLDER = os.path.join(
    PROJECT_ROOT,
    "frontend",
    "static",
    "detection_results"
)


os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)

os.makedirs(
    SNAPSHOT_FOLDER,
    exist_ok=True
)

os.makedirs(
    SUMMARY_FOLDER,
    exist_ok=True
)


# =====================================================
# RUN DETECTION
# =====================================================

def run_detection(video_path):

    print("=" * 70)
    print("Starting AI Detection")
    print("Input :", video_path)
    print("=" * 70)

    # -------------------------------------------------
    # Check input
    # -------------------------------------------------

    if not os.path.exists(video_path):

        return {
            "success": False,
            "message": "Video file not found."
        }

    try:

        # -------------------------------------------------
        # Video information
        # -------------------------------------------------

        video_name = os.path.basename(
            video_path
        )

        video_name_without_extension = (
            os.path.splitext(video_name)[0]
        )

        output_filename = (
            f"output_{video_name_without_extension}.mp4"
        )

        output_video = os.path.join(
            OUTPUT_FOLDER,
            output_filename
        )

        # -------------------------------------------------
        # Summary file
        # -------------------------------------------------

        summary_filename = (
            f"summary_{video_name_without_extension}.json"
        )

        summary_path = os.path.join(
            SUMMARY_FOLDER,
            summary_filename
        )

        # -------------------------------------------------
        # Remove old files from a previous run
        # -------------------------------------------------

        if os.path.exists(output_video):

            try:

                os.remove(
                    output_video
                )

            except Exception:

                pass

        if os.path.exists(summary_path):

            try:

                os.remove(
                    summary_path
                )

            except Exception:

                pass

        # -------------------------------------------------
        # Launch AI Detection Engine
        # -------------------------------------------------

        print()
        print("=" * 70)
        print("Launching AI Detection Engine...")
        print("=" * 70)

        process = subprocess.run(

            [
                sys.executable,

                os.path.join(
                    PROJECT_ROOT,
                    "detection",
                    "real_time_detection.py"
                ),

                video_path

                
            ],

            text=True,

            capture_output=True,

            cwd=PROJECT_ROOT

        )

        # -------------------------------------------------
        # Display engine output
        # -------------------------------------------------

        if process.stdout:

            print(
                process.stdout
            )

        if process.stderr:

            print(
                process.stderr
            )

        print("=" * 70)
        print("AI Detection Engine Finished")
        print("Return Code :", process.returncode)
        print("=" * 70)

        # -------------------------------------------------
        # Detection engine failed
        # -------------------------------------------------

        if process.returncode != 0:

            return {

                "success": False,

                "message": (
                    process.stderr
                    or
                    process.stdout
                    or
                    "AI Detection Engine Failed."
                )

            }

        # -------------------------------------------------
        # Verify processed video
        # -------------------------------------------------

        if not os.path.exists(output_video):

            return {

                "success": False,

                "message": (
                    "Processed video was not generated."
                )

            }

        # -------------------------------------------------
        # Verify summary
        # -------------------------------------------------

        if not os.path.exists(summary_path):

            return {

                "success": False,

                "message": (
                    "Detection result summary "
                    "was not generated."
                )

            }

        # -------------------------------------------------
        # Read AUTHORITATIVE result
        # -------------------------------------------------

        with open(
            summary_path,
            "r",
            encoding="utf-8"
        ) as file:

            result = json.load(
                file
            )

        # -------------------------------------------------
        # Safety validation
        # -------------------------------------------------

        if not isinstance(
            result,
            dict
        ):

            return {

                "success": False,

                "message": (
                    "Invalid detection result."
                )

            }

        # -------------------------------------------------
        # Make sure required fields exist
        # -------------------------------------------------

        result.setdefault(
            "success",
            True
        )

        result.setdefault(
            "status",
            "NORMAL"
        )

        result.setdefault(
            "message",
            "No abnormal activity detected."
        )

        result.setdefault(
            "anomaly_detected",
            False
        )

        result.setdefault(
            "confidence",
            0.0
        )

        result.setdefault(
            "fusion_score",
            0.0
        )

        result.setdefault(
            "alarm_status",
            "NOT TRIGGERED"
        )

        result.setdefault(
            "snapshot_status",
            "NOT REQUIRED"
        )

        result.setdefault(
            "snapshot_path",
            ""
        )

        result.setdefault(
            "timestamp",
            ""
        )

        # -------------------------------------------------
        # Normalize numeric values
        # -------------------------------------------------

        result["confidence"] = float(
            result["confidence"]
        )

        result["fusion_score"] = float(
            result["fusion_score"]
        )

        # -------------------------------------------------
        # Browser video path
        # -------------------------------------------------

        result["video_path"] = (
            "processed_videos/"
            + output_filename
        )

        result["video_filename"] = (
            output_filename
        )

        # -------------------------------------------------
        # Snapshot URLs
        # -------------------------------------------------

        snapshot_urls = []

        snapshot_path = result.get(
            "snapshot_path",
            ""
        )

        if snapshot_path:

            snapshot_filename = os.path.basename(
                snapshot_path
            )

            actual_snapshot = os.path.join(
                SNAPSHOT_FOLDER,
                snapshot_filename
            )

            if os.path.exists(
                actual_snapshot
            ):

                snapshot_urls.append(
                    "saved_incidents/"
                    + snapshot_filename
                )

        result["snapshots"] = snapshot_urls

        # -------------------------------------------------
        # Compatibility incident object
        # -------------------------------------------------

        incident = result.get(
            "incident"
        )

        if not isinstance(
            incident,
            dict
        ):

            incident = {}

        incident["incident_type"] = (
            "ANOMALY"
            if result["anomaly_detected"]
            else
            "NORMAL"
        )

        incident["confidence"] = (
            result["confidence"]
        )

        incident["score"] = (
            result["fusion_score"]
        )

        incident["alarm_status"] = (
            result["alarm_status"]
        )

        incident["timestamp"] = (
            result["timestamp"]
        )

        incident["snapshot_path"] = (
            result["snapshot_path"]
        )

        incident["video_path"] = (
            result["video_path"]
        )

        result["incident"] = incident

        # -------------------------------------------------
        # Final validation
        # -------------------------------------------------

        if result["anomaly_detected"]:

            result["status"] = (
                "ANOMALY DETECTED"
            )

        else:

            result["status"] = (
                "NORMAL"
            )

            # A normal video must NEVER inherit
            # values from an older incident.

            result["confidence"] = 0.0

            result["fusion_score"] = 0.0

            result["alarm_status"] = (
                "NOT TRIGGERED"
            )

            result["snapshot_status"] = (
                "NOT REQUIRED"
            )

            result["snapshot_path"] = ""

            result["snapshots"] = []

            result["incident"] = {

                "incident_type": "NORMAL",

                "confidence": 0.0,

                "score": 0.0,

                "alarm_status": (
                    "NOT TRIGGERED"
                ),

                "timestamp": result["timestamp"],

                "snapshot_path": "",

                "video_path": (
                    result["video_path"]
                )

            }

        # -------------------------------------------------
        # Print final result
        # -------------------------------------------------

        print()
        print("=" * 70)
        print("AUTHORITATIVE AI RESULT")
        print("=" * 70)

        print(
            "Status          :",
            result["status"]
        )

        print(
            "Confidence      :",
            result["confidence"]
        )

        print(
            "Fusion Score    :",
            result["fusion_score"]
        )

        print(
            "Alarm           :",
            result["alarm_status"]
        )

        print(
            "Snapshot        :",
            result["snapshot_status"]
        )

        print(
            "Processed Video :",
            result["video_path"]
        )

        print("=" * 70)

        return result

    except Exception as e:

        print(
            traceback.format_exc()
        )

        return {

            "success": False,

            "message": str(e)

        }